### PR TITLE
Add `contact_info` to ServiceInfo.

### PR DESCRIPTION
**Pull request by tetron**
This is simply an additional field to ServiceInfo that should provide a way to contact the operator of a given WES endpoint.

### CODE REVIEW

**Comment by geoffjentry** [comment]
Did this come out of the security group's requirements?

**Comment by mckinsel** [comment]
I think this was to answer "What mechanism will you implement to enable users of this product to report discovered vulnerabilities?"

**Comment by tetron** [comment]
Yes.

**Comment by geoffjentry** [comment]
Ok, that's what I figured. In that case I'd suggest being more explicit about the purpose. If I hadn't been on the call today I'd have assumed this is one of those rando things which is a good enough idea on the surface but where one can't do everything :)

**Comment by tetron** [comment]
@geoffjentry I added another sentence, what do you think?

**Comment by geoffjentry** [comment]
Looks good, thanks

**Pull request merged**
