### PR TITLE
Switch to github actions and add Open API lining and validation 

### LINKED ISSUE #178: Migrate build docs over to github actions
The decision has been made to move cloud work stream repos over to using github actions for performing any CI operations as opposed to Travis CI. [This Pr](https://github.com/ga4gh/data-repository-service-schemas/pull/379/files) for DRS has already done the heavy lift which we should port over to the WES repo

### LINKED ISSUE #194: Integrate OpenAPI validator into CI
To be able to merge feature and release branches with confidence, the continuous integration pipeline should run an OpenAPI validator on the specification.

### PR DESCRIPTION
**Pull request by vsmalladi**
Switch to github actions: Closes #178 
Adds in Open API ci: Closes #194

### CODE REVIEW

**Review by patmagee — APPROVED** [review]
This looks good to me, but i would be interested to know what @jaeddy thinks since the original ticket was created/assigned to him

**Comment by uniqueg** [comment]
Looks good to me too. But you may wanna consider adding some spec checking as we have recently introduced into TES CI: https://github.com/ga4gh/task-execution-schemas/pull/181/files

But could of course also go in a future PR...

**Comment by vsmalladi** [comment]
@uniqueg Great idea. I just added it to the PR.

**Comment by vsmalladi** [comment]
@patmagee and @uniqueg  ready for a quick re-review

**Comment by uniqueg** [comment]
Great :)

**Review by patmagee — APPROVED** [review]

**Pull request merged**
