### PR TITLE
Remove Definition and Reference Python Code

### PR DESCRIPTION
**Pull request by patmagee**
The swagger definition of WES has been deprecated in favor of openapi 3.0, however it was kept in the repo for backwards compatibility. Speaking with a number of people at plenary it came up that instead of being helpful, this has actually caused some issues among implementors. Since the swagger API is outdated it can easily lead to implementing the "WRONG" api. Additionally (I have felt this as well), there is no clear direction of what spec doc should be modified when implementing a PR leading to implementors editing both docs.

Additionally, I have removed the Reference python code. This code used to be built as part of the travis build process, but has been commented out for sometime and is outdated with the current spec. This has also been superseded by the WES GA4GH starter kit (https://github.com/ga4gh/ga4gh-starter-kit-wes), which is more actively maintained and updated.

### CODE REVIEW

**Review by jaeddy — APPROVED** [review]
I think preserving the Swagger spec was related to [this issue](https://github.com/ga4gh/workflow-execution-service-schemas/issues/134), but I agree that it makes more sense to only keep the OpenAPI from the current version moving forward.

If anyone ever wants to look at the original Swagger from the v1.0 release, it can be found on the tag branch or in Zenodo.

**Review by wleepang — APPROVED** [review]

**Comment by patmagee** [comment]
@jaeddy @wleepang I apologize, it looks like local state from a divergent develop branch sneaked its way in. I have updated the PR to remove those extra files, if you to take one additional view

**Review by wleepang — APPROVED** [review]

**Review by jaeddy — APPROVED** [review]
Was wondering about the Workflow Inputs stuff — makes more sense now. 🙂

**Comment by uniqueg** [comment]
Yes - finally!! 😆

**Pull request merged**
