### PR TITLE
removed WesObject from the schema

### PR DESCRIPTION
**Pull request by delagoya**
Resolves issue #96 by removing WesObject from the schema.

### CODE REVIEW

**Comment by dglazer** [comment]
Thanks Angel. I'm pretty new to OpenAPI, but I would have expected the two references to WesObject to be replaced by `type: string` (not `type: object`). Is there a reason to use an object without properties, instead of a string?

**Comment by delagoya** [comment]
It was my reading of the conversation during the call yesterday that consensus landed on a JSON object in lieu of string type. The rational was that a String would require inspection and proper deserialization on the consumer, whereas a JSON object is understood to be a single parser. 

Having said that, I am also new to Swagger/OpenAPI! In my naive understanding I was assuming that both of these would be valid parameter values: 

```json 
{
    "param1" : "value1", 
    "param2": 2
}
```
```json
{
    "param1" :  { 
         "sub_param1": "value1", 
         "sub_param2": "value2"
    }, 
    "param2":  [1, 2, 3]
}
```
 

So if this is not the right way of encoding a arbitrary JSON object as a parameter type, someone with actual experience should comment.

**Comment by dglazer** [comment]
Poking around a bit more I think you're right. Be great to have some expert confirmation.

**Comment by tetron** [comment]
> It was my reading of the conversation during the call yesterday that consensus landed on a JSON object in lieu of string type. The rational was that a String would require inspection and proper deserialization on the consumer, whereas a JSON object is understood to be a single parser.

That's correct.

> So if this is not the right way of encoding a arbitrary JSON object as a parameter type, someone with actual experience should comment.

Based on https://swagger.io/docs/specification/data-models/data-types/#free-form I think you have it right.

**Pull request merged**
